# Generated by Django 4.2 on 2023-04-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_upload_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_available',
            field=models.BooleanField(default=True),
        ),
    ]
