# Generated by Django 4.2 on 2023-04-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_book_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(default='https://pngimg.com/uploads/book/book_PNG2111.png', max_length=2083),
        ),
    ]
